spring.application.name=online examination system

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/examination?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=sainfinity

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=1010
spring.jpa.show-sql= true

# JWT Configuration
jwt.secret=dGhpc2lzYXNlY3VyZWtleWZvcmp3dHNpZ25pbmdwdXJwb3Nlc29ubHlhbmRpdHNob3VsZGJlYXRsZWFzdDI1NmJpdHNsb25nZm9yaG1hY3NoYTI1Ng==


# Email Configuration
# Gmail SMTP Configuration (example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kalanasandeep55@gmail.com
spring.mail.password=txza gjek wfjz nwsb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Application Frontend URL
app.frontend.url=http://localhost:5173

# Email Template Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# Async Configuration
spring.task.execution.pool.core-size=2
spring.task.execution.pool.max-size=5
spring.task.execution.pool.queue-capacity=100
spring.task.execution.thread-name-prefix=async-




